model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 128
  img_size: 64
  loss_type: 'H'
  beta: 5.

exp_params:
  dataset: rbc
  data_path: "datasets/rbc.h5"
  data_path_val: "datasets/rbc_val.h5"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_H_RBC"
  manual_seed: 1265
